version: "3"
services:
  node:
    build:
      context: .
      dockerfile: node/Dockerfile
    container_name: nodeJS
    volumes: 
      - ./app:/usr/src/app
      - ./app/node_modules:/usr/src/app/node_modules
    expose:
      - 3000
    ports:
      - 3000:3000